config/routes.rb
Rails.application.routes.draw do

  #Index de tout le site
  root to: 'home#index'

  #Partie admin
  namespace :admin do
    resources :carousels
    resources :user, except: :index
    get '/users' => 'user#index', as: :admin_user_index
  end
  get '/admin' => 'admin#index', as: :admin_root

  #Différentes pages disponibles
  resources :magazines, path: 'webzines' do
    resources :pages
  end

  resources :mangas do
    resources :chapters, except: :show do
      resources :pejis, except: :show
    end
  end

  get '/mangas/:manga_id/:id' => 'chapters#show', as: :chapter
  get '/mangas/:manga_id/:chapter_id/:id' => 'pejis#show', as: :peji


  resources :presentations
  resources :blog

  # Partie contact
  get '/contact', to: 'contacts#new', as: :new_contact
  post '/contact', to: 'contacts#create', as: :contacts

  #Login + paramétrage des membres de KD
  devise_for :users
  get 'user/create'
  get '/membres' => 'user#index', as: :membres
  get '/membre/:id' => 'user#show', as: :membre
  get '/user/:id/edit_password' => 'user#password', as: :change_password
  resources :user, :controller => 'user'

  get '/mentions-legales', to: 'home#cgu', as: :cgu


end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  belongs_to :user
  mount_uploader :illu1, BlogUploader
  mount_uploader :illu2, BlogUploader
end

app/models/chapter.rb
class Chapter < ApplicationRecord

  has_many :pejis, :dependent => :destroy
  belongs_to :manga
  mount_uploader :apercu, ThumbnailUploader

end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :nom, :sujet, :email, :message

  validates :nom, :objet, :sujet, :email, :message, presence: true
  validates :email, :format => { :with => %r{.+@.+\..+} }, allow_blank: true

  def persisted?
    false
  end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

end

app/models/magazine.rb
class Magazine < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader
  has_many :pages, :inverse_of => :magazine, :dependent => :destroy
  validates_uniqueness_of :slug


  def first_page
    self.pages.find_by(page_number: 1)
  end

end

app/models/manga.rb
class Manga < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  validates_presence_of :slug

  has_many :chapters , :inverse_of => :manga, :dependent => :destroy
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader

  has_and_belongs_to_many :users

end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :magazine
  validates_presence_of :magazine
  mount_uploader :image, PageUploader

  def previous
    self.class.where(page_number: (first.page_number - 1), magazine: first.magazine)
  end

  def next
    self.class.where(page_number: (first.page_number + 1), magazine: first.magazine)
  end

end

app/models/peji.rb
class Peji < ApplicationRecord

  belongs_to :chapter, :inverse_of => :pejis
  validates_presence_of :chapter
  mount_uploader :image, ScansUploader

  def previous
    self.class.where('scan_number < ?', scan_number).limit(1).first
  end

  def next
    self.class.where('scan_number > ?', scan_number).limit(1).last
  end

end

app/models/presentation.rb
class Presentation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_and_belongs_to_many :mangas
  has_many :blogs

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_manga, only: [:show, :edit, :update, :destroy]


  def index
    @titre = 'Mangas'
    @pair = Manga.where(:pair => true)
    @impair = Manga.where(:pair => false)
  end

  def show
    @titre = @manga.titre
  end

  def new
    @titre = 'Nouveau manga'
    @manga = Manga.new
  end

  def edit
    @titre = 'Modifier '+@manga.titre
  end

  def create
    @manga = Manga.new(manga_params)

    if @manga.save
      @manga.users.push(current_user)
      redirect_to @manga, notice: 'Manga was successfully created.'
    else
      render :new
    end
  end

  def update
    if @manga.update(manga_params)
      if @manga.users.empty?
        @manga.users.push(current_user)
      end
      redirect_to @manga, notice: 'Manga was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @manga.destroy
    redirect_to mangas_url, notice: 'Manga was successfully destroyed.'
  end

  private
    def set_manga
      @manga = Manga.friendly.find(params[:id])
    end

    def manga_params
      params.require(:manga).permit(:titre, :description, :apercu, :banniere, :pair, :date_parution, :user_ids =>[])
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Retourne un titre
  def titre
    base_titre = 'Kippon Dream'
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
  def first_page
    self.pages.find_by(page_number: 1)
  end
end

app/helpers/mangas_helper.rb
module MangasHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pejis_helper.rb
module PejisHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/mangas/_form.html.erb
<%= form_for(manga) do |f| %>
  <% if manga.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manga.errors.count, "error") %> prohibited this manga from being saved:</h2>

      <ul>
      <% manga.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :users %>
    <%= f.select :user_ids, User.all_except(current_user).collect { |u| [u.username, u.id] }, {include_blank: true}, {multiple: true} %>
  </div>

  <div class="field">
    <%= f.label :date_parution %>
    <%= f.date_select :date_parution, start_year: 2010, order: [ :day, :month, :year] %>
  </div>

  <div class="field">
    <%= f.label :pair, "Pair ou impaire ?" %>
    <%= f.radio_button :pair, true %>
    <%= label :pair, 'Pair' %>
    <%= f.radio_button :pair, false %>
    <%= label :pair, 'Impair' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :maxlength => 300 %>
  </div>

  <div class="field">
    <%= f.label :apercu %>
    <%= f.file_field :apercu %>
  </div>

  <div class="field">
    <%= f.label :banniere %>
    <%= f.file_field :banniere %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mangas/edit.html.erb
<h1>Editing Manga</h1>

<%= render 'form', manga: @manga %>

<%= link_to 'Show', @manga %> |
<%= link_to 'Back', mangas_path %>

app/views/mangas/index.html.erb
<div class="series-container">
  <div class="cadre-container">
    <h2>Séries</h2>
    <p>Voici l'ensemble de nos séries prépubliées dans le Kippon Dream ! A partir du numéro 06 elles
      sont partagées entre numéros pairs et impairs, vous pouvez donc les retrouver comme cela !</p>
    <div class="flex-series">
      <div class="series series-paires">
        <p>Séries paires</p>

        <% @pair.each do |p| %>
          <% if p.chapters.size > 0 %>
          <div class="serie kd-animate">
            <div class="container-img">
              <%= image_tag p.apercu, size: '158x218' %>
            </div>
            <div class="container-texte">
              <h3><%= p.titre %></h3>
              <p><%= simple_format(p.description) %></p>
              <%= link_to 'lire la suite', peji_path(manga_id: p, chapter_id: p.chapters.size, id: 1), title: 'Lire '+p.titre %>
            </div>
          </div> <!-- .serie -->
          <% end %>
        <% end %>

      </div> <!-- .series .series-paires -->

      <div class="barre"></div>

      <div class="series series-impaires">
        <p>Séries impaires</p>
        <% @impair.each do |i| %>
          <% if i.chapters.size > 0 %>
          <div class="serie kd-animate">
            <div class="container-img">
              <%= image_tag i.apercu, size: '158x218' %>
            </div>
            <div class="container-texte">
              <h3><%= i.titre %></h3>
              <p><%= simple_format(i.description) %></p>
              <%= link_to 'lire la suite', peji_path(manga_id: i, chapter_id: i.chapters.size, id: 1), title: 'Lire '+i.titre %>
            </div>
          </div> <!-- .serie -->
          <% end %>
        <% end %>

      </div> <!-- .series .series-impaires -->
    </div>

  </div>
</div>

app/views/mangas/new.html.erb
<h1>New Manga</h1>

<%= render 'form', manga: @manga %>

<%= link_to 'Back', mangas_path %>

app/views/mangas/show.html.erb
<p>
  <strong>Titre:</strong>
  <%= @manga.titre %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@manga.description) %>
</p>

<p>
  <strong>Apercu:</strong>
  <%= image_tag @manga.apercu, size: '200x200' %>
</p>

<p>
  <strong>Banniere:</strong>
  <%= image_tag @manga.banniere, size: '200x200' %>
</p>

<p><strong>Chapitres :</strong></p>
<% @manga.chapters.each do |c| %>
    <li>
      <%= link_to c.titre, peji_path(manga_id: @manga.slug, chapter_id: c.chapter_number, id: 1) %>
      <% if @manga.users.include? current_user %>
        (<%= link_to 'Modifier', edit_manga_chapter_path(@manga, c.chapter_number) %>
        |
        <%= link_to 'Supprimer', manga_chapter_path(@manga, c.chapter_number), :method => :delete, data: {confirm: 'Le chapitre et son contenu seront supprimer, confirmer ?'} %>)
      <% end %>
    </li>
<% end %>

<p>
  <strong>Users:</strong>
  <%= @manga.users.map(&:username).join(" - ") %>
</p>

<%= link_to 'Ajouter un chapitre', new_manga_chapter_path(@manga) %> <br />

<%= link_to 'Edit', edit_manga_path(@manga) %> |
<%= link_to 'Back', mangas_path %>