config/routes.rb
Rails.application.routes.draw do

  #Index de tout le site
  root to: 'home#index'

  #Partie admin
  namespace :admin do
    resources :carousels
    resources :user, except: :index
    get '/users' => 'user#index', as: :admin_user_index
  end
  get '/admin' => 'admin#index', as: :admin_root

  #Différentes pages disponibles
  resources :magazines, path: 'webzines' do
    resources :pages
  end

  resources :mangas do
    resources :chapters, except: :show do
      resources :pejis, except: :show
    end
  end

  get '/mangas/:manga_id/:id' => 'chapters#show', as: :chapter
  get '/mangas/:manga_id/:chapter_id/:id' => 'pejis#show', as: :peji


  resources :presentations
  resources :blog

  # Partie contact
  get '/contact', to: 'contacts#new', as: :new_contact
  post '/contact', to: 'contacts#create', as: :contacts

  #Login + paramétrage des membres de KD
  devise_for :users
  get 'user/create'
  get '/membres' => 'user#index', as: :membres
  get '/membre/:id' => 'user#show', as: :membre
  get '/user/:id/edit_password' => 'user#password', as: :change_password
  resources :user, :controller => 'user'

  get '/mentions-legales', to: 'home#cgu', as: :cgu


end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  belongs_to :user
  mount_uploader :illu1, BlogUploader
  mount_uploader :illu2, BlogUploader
end

app/models/chapter.rb
class Chapter < ApplicationRecord

  has_many :pejis, :dependent => :destroy
  belongs_to :manga
  mount_uploader :apercu, ThumbnailUploader

end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :nom, :sujet, :email, :message

  validates :nom, :objet, :sujet, :email, :message, presence: true
  validates :email, :format => { :with => %r{.+@.+\..+} }, allow_blank: true

  def persisted?
    false
  end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

end

app/models/magazine.rb
class Magazine < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader
  has_many :pages, :inverse_of => :magazine, :dependent => :destroy
  validates_uniqueness_of :slug


  def first_page
    self.pages.find_by(page_number: 1)
  end

end

app/models/manga.rb
class Manga < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  validates_presence_of :slug

  has_many :chapters , :inverse_of => :manga, :dependent => :destroy
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader

  has_and_belongs_to_many :users

end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :magazine
  validates_presence_of :magazine
  mount_uploader :image, PageUploader

  def previous
    self.class.where(page_number: (first.page_number - 1), magazine: first.magazine)
  end

  def next
    self.class.where(page_number: (first.page_number + 1), magazine: first.magazine)
  end

end

app/models/peji.rb
class Peji < ApplicationRecord

  belongs_to :chapter, :inverse_of => :pejis
  validates_presence_of :chapter
  mount_uploader :image, ScansUploader

  def previous
    self.class.where('scan_number < ?', scan_number).limit(1).first
  end

  def next
    self.class.where('scan_number > ?', scan_number).limit(1).last
  end

end

app/models/presentation.rb
class Presentation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_and_belongs_to_many :mangas
  has_many :blogs

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  before_action :set_admin_user, except: :index

  def index
    @admin_users = User.all
  end

  def show
  end

  def edit
  end

  private

  def set_admin_user
    @admin_user = User.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_user!, except: :index
  before_action :set_user, only: [:show, :edit, :update, :password]
  before_action :check_user, only: [:edit, :password]

  def new
    @titre = 'Nouveau membre'
    @user = User.new
  end

  def index
    @titre = 'Membres'
    @users = User.order('username ASC')
  end

  def edit

  end

  def password
    @titre = 'Modifiez votre mot de passe'
  end

  def show
    @titre = @user.username
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_root_path, notice: 'Utilisateur créé'
    else
      render :action => 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_root_path, notice: 'Profil mit à jour'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :avatar, :is_femme,
    :date_naissance, :role, :description)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def check_user
    if current_user.id != params[:id].to_i
      redirect_to membres_path, alert: 'Propriété privée.'
    end
  end

end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Retourne un titre
  def titre
    base_titre = 'Kippon Dream'
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
  def first_page
    self.pages.find_by(page_number: 1)
  end
end

app/helpers/mangas_helper.rb
module MangasHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pejis_helper.rb
module PejisHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/user/edit.html.erb
<h1>Admin::User#edit</h1>
<p>Find me in app/views/admin/user/edit.html.erb</p>

app/views/admin/user/index.html.erb
<h1>UTILISATEURS - PARTIE ADMIN</h1>
<p>Liste des utilisateurs :</p>


<table>
  <tr>
    <th>Avatar</th>
    <th>Pseudo</th>
    <th>Adresse email</th>
    <th>Rôle</th>
    <th>Action</th>
  </tr>
  <% @admin_users.each do |u| %>
    <tr>
      <td>
        <%= image_tag u.avatar, size: '50x50' %>
      </td>
      <td>
        <%= u.username %>
      </td>
      <td>
        <%= u.email %>
      </td>
      <td>
        <%= u.role %>
      </td>
      <td>
        <%= link_to 'Voir', admin_user_path(u) %>
        <a href="#">Modifier</a>
        <a href="#">Supprimer</a>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/user/show.html.erb
<h1>PROFIL DE <%= @admin_user.username.upcase %></h1>

<ul>
  <li>Avatar : <%= image_tag @admin_user.avatar, size: '70x70' %></li>
  <li>Pseudo : <%= @admin_user.username %></li>
  <li>Adresse e-mail : <%= @admin_user.email %></li>
  <li>Dernière connexion : <%= @admin_user.last_sign_in_at.strftime('%d / %m / %Y à %H:%M') %></li>
  <li>Profil créé le : <%= @admin_user.created_at.strftime('%d / %m / %Y') %></li>
  <li><%= @admin_user.is_femme? ? 'Femme' : 'Homme' %></li>
  <li>Rôle : <%= @admin_user.role %></li>
</ul>

app/views/user/edit.html.erb
<h1>Editer son profil</h1>

<%= form_for @user, :html => {:class=>'form-admin'} do |f| %>

    <p>
      <%= f.text_field :username, :placeholder=>'Ton pseudo', :class=>'input-text' %>
    </p>

    <p>
      <%= f.text_field :email, :placeholder=>'Ton email', :class=>'input-text' %>
    </p>

    <p>
      <%= f.label :avatar %>
      <%= f.file_field :avatar %>
    </p>

    <p>
      <%= f.label :is_femme %>
      <%= f.check_box :is_femme %>
    </p>

    <p>
      <% if @user.avatar %>
          <%= image_tag @user.avatar, size: '100x100' %>
      <% end %>
    </p>

    <div class="field">
      <%= f.text_area :description, :class=>'input-text', :placeholder=>"Décris-toi ici, ça va s'afficher dans tes articles
      et dans ta présentation de la page membre" %>
    </div>

    <p>
      <%= f.label :date_naissance %>
      <%= f.date_select :date_naissance, {:start_year => 1990, order: [:day, :month, :year] } %>
    </p>

    <p>
      <%= f.label :role %>
      <%= f.select :role, options_for_select(%w[Dieu Staff Auteur], 'Auteur') %>
    </p>

  <%= f.submit "Editer mon profil", class: 'blue-button' %>
<% end %>

<%= link_to 'Modifier le mot de passe', change_password_path(@user) %>

app/views/user/index.html.erb
<h3 class="members-title">Membres & Auteurs</h3>

<section class="staff">
  <% @users.each do |u| %>
  <div class="membre is-collapsed">
    <div class="image-basic">
      <h4><%= u.username %></h4>
      <%= image_tag u.avatar, class: 'membre-img' %>
      <div class="arrow-up"></div>
    </div>
    <div class="image-expand">
      <div class="membre-presentation">
        <p><%= simple_format(u.description) %></p>
        <div class="projets-articles">
          <div class="membre-projets">
            <h5>Ses projets :</h5>
            <ul>
              <% u.mangas.each do |m| %>
                  <li><%= link_to m.titre, peji_path(manga_id: m.slug, chapter_id: 1, id: 1), title: 'Lire '+m.titre %></li>
              <% end %>
            </ul>
          </div>
          <div class="articles-recents">
            <h5>Ses articles récents :</h5>
            <ul>
              <% u.blogs.each do |b| %>
                  <li><%= link_to b.titre, b, title: 'Lire '+b.titre %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div> <!-- .membre-presentation -->
    </div> <!-- .image-expand -->
  </div> <!-- .membre -->
  <% end %>
</section>

app/views/user/new.html.erb
<%= form_for @user, :url => user_index_path do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password  %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation  %>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
  </p>

  <p>
    <%= f.label :role %>
    <%= f.select :role, options_for_select(%w[Dieu Staff Auteur], 'Auteur') %>
  </p>

  <p><%= f.submit 'Save' %></p>
<% end %>

app/views/user/password.html.erb
<h1>Je veux changer mon mot de passe !</h1>
<%= form_for @user, :html => {:class=>'form-admin'} do |f| %>
    <p>
      <%= f.password_field :password, :placeholder=>'Nouveau mot de passe', :class=>'input-text', :id=>'password' %>
    </p>
    <p class="error-toggle">Mot de passe invalide. Il doit faire au moins 2 caractères et max 15 caractères, contenir au moins un nombre
      et un caractère spécial (ex: a1B2^c3%)</p>

    <p>
      <%= f.password_field :password_confirmation, :placeholder=>'Confirmez votre nouveau mot de passe', :id=>'password-confirm', :class=>'input-text' %>
    </p>
    <p class="error-toggle">Mot de passe invalide. Il doit faire au moins 2 caractères et max 15 caractères, contenir au moins un nombre
      et un caractère spécial (ex: a1B2^c3%)</p>

    <%= f.submit "Changer mon mot de passe", class: 'blue-button' %>


<% end %>

app/views/user/show.html.erb
<h1>Profiiiiil</h1>

<%= @user.username %><br />
<%= image_tag @user.avatar, size: '100x100' if @user.avatar %><br />
<%= @user.date_naissance.strftime('%d / %m / %Y') if @user.date_naissance %><br />
<%= @user.is_femme ? 'Femme' : 'Homme' %><br />
<%= @user.email %><br />
<%= @user.role if @user.role %><br />

<%= link_to 'Modifier profil', edit_user_path, id: current_user.id %>