config/routes.rb
Rails.application.routes.draw do

  #Index de tout le site
  root to: 'home#index'

  #Partie admin
  namespace :admin do
    resources :carousels
    resources :user, except: :index
    get '/users' => 'user#index', as: :admin_user_index
  end
  get '/admin' => 'admin#index', as: :admin_root

  #Différentes pages disponibles
  resources :magazines, path: 'webzines' do
    resources :pages
  end

  resources :mangas do
    resources :chapters, except: :show do
      resources :pejis, except: :show
    end
  end

  get '/mangas/:manga_id/:id' => 'chapters#show', as: :chapter
  get '/mangas/:manga_id/:chapter_id/:id' => 'pejis#show', as: :peji


  resources :presentations
  resources :blog

  # Partie contact
  get '/contact', to: 'contacts#new', as: :new_contact
  post '/contact', to: 'contacts#create', as: :contacts

  #Login + paramétrage des membres de KD
  devise_for :users
  get 'user/create'
  get '/membres' => 'user#index', as: :membres
  get '/membre/:id' => 'user#show', as: :membre
  get '/user/:id/edit_password' => 'user#password', as: :change_password
  resources :user, :controller => 'user'

  get '/mentions-legales', to: 'home#cgu', as: :cgu


end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  belongs_to :user
  mount_uploader :illu1, BlogUploader
  mount_uploader :illu2, BlogUploader
end

app/models/chapter.rb
class Chapter < ApplicationRecord

  has_many :pejis, :dependent => :destroy
  belongs_to :manga
  mount_uploader :apercu, ThumbnailUploader

end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :nom, :sujet, :email, :message

  validates :nom, :objet, :sujet, :email, :message, presence: true
  validates :email, :format => { :with => %r{.+@.+\..+} }, allow_blank: true

  def persisted?
    false
  end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

end

app/models/magazine.rb
class Magazine < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader
  has_many :pages, :inverse_of => :magazine, :dependent => :destroy
  validates_uniqueness_of :slug


  def first_page
    self.pages.find_by(page_number: 1)
  end

end

app/models/manga.rb
class Manga < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  validates_presence_of :slug

  has_many :chapters , :inverse_of => :manga, :dependent => :destroy
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader

  has_and_belongs_to_many :users

end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :magazine
  validates_presence_of :magazine
  mount_uploader :image, PageUploader

  def previous
    self.class.where(page_number: (first.page_number - 1), magazine: first.magazine)
  end

  def next
    self.class.where(page_number: (first.page_number + 1), magazine: first.magazine)
  end

end

app/models/peji.rb
class Peji < ApplicationRecord

  belongs_to :chapter, :inverse_of => :pejis
  validates_presence_of :chapter
  mount_uploader :image, ScansUploader

  def previous
    self.class.where('scan_number < ?', scan_number).limit(1).first
  end

  def next
    self.class.where('scan_number > ?', scan_number).limit(1).last
  end

end

app/models/presentation.rb
class Presentation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_and_belongs_to_many :mangas
  has_many :blogs

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/pejis_controller.rb
class PejisController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_peji, only: [:show, :edit, :update, :destroy]

  layout 'reader', only: :show

  def index
    @pejis = Peji.all
  end

  def show
    @titre = @manga.titre
  end

  def new
    @peji = Peji.new
  end

  def edit
  end

  def create
    @peji = Peji.new(peji_params)

    if @peji.save
      redirect_to @peji, notice: 'Peji was successfully created.'
    else
      render :new
    end
  end

  def update
    if @peji.update(peji_params)
      redirect_to @peji, notice: 'Peji was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @peji.destroy
    redirect_to pejis_url, notice: 'Peji was successfully destroyed.'
  end

  private

    def set_peji
      @manga = Manga.find_by(slug: params[:manga_id])
      @chapter = @manga.chapters.find_by(chapter_number: params[:chapter_id])
      @peji = @chapter.pejis.find_by(scan_number: params[:id])
    end

    def peji_params
      params.require(:peji).permit(:image, :manga_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Retourne un titre
  def titre
    base_titre = 'Kippon Dream'
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
  def first_page
    self.pages.find_by(page_number: 1)
  end
end

app/helpers/mangas_helper.rb
module MangasHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pejis_helper.rb
module PejisHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/pejis/_form.html.erb
<%= form_for(peji) do |f| %>
  <% if peji.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(peji.errors.count, "error") %> prohibited this peji from being saved:</h2>

      <ul>
      <% peji.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :manga_id %>
    <%= f.number_field :manga_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pejis/edit.html.erb
<h1>Editing Peji</h1>

<%= render 'form', peji: @peji %>

<%= link_to 'Show', @peji %> |
<%= link_to 'Back', pejis_path %>

app/views/pejis/index.html.erb
<h1>Pejis</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Manga</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pejis.each do |peji| %>
      <tr>
        <td><%= peji.image %></td>
        <td><%= peji.manga_id %></td>
        <td><%= link_to 'Show', peji %></td>
        <td><%= link_to 'Edit', edit_peji_path(peji) %></td>
        <td><%= link_to 'Destroy', peji, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peji', new_peji_path %>

app/views/pejis/new.html.erb
<h1>New Peji</h1>

<%= render 'form', peji: @peji %>

<%= link_to 'Back', pejis_path %>

app/views/pejis/show.html.erb
<div class="pejis-reader">

  <div class="img-manga">
    <%= image_tag @peji.image %>
    <% if params[:id].to_i > 1 %>
      <%= link_to peji_path(manga_id: @manga.slug, chapter_id: @chapter.chapter_number, id: params[:id].to_i - 1), title: 'Précédent' do %>
      <div class="arrow-back">
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
      </div>
      <% end %>
    <% end %>

    <% if params[:id].to_i < @chapter.pejis.size %>
      <%= link_to peji_path(manga_id: @manga.slug, chapter_id: @chapter.chapter_number, id: params[:id].to_i + 1), title: 'Suivant' do %>
      <div class="arrow-next">
        <i class="fa fa-arrow-right" aria-hidden="true"></i>
      </div>
      <% end %>
    <% end %>
  </div>

  <!-- @Todo : Vérifier si les liens précédents et suivants fonctionnent réellement... -->

  <div class="next-prev">
    <%= link_to '< Précédent', peji_path(id: @peji.previous.scan_number, chapter_id: @chapter.chapter_number), title: 'Précédent' if @peji.previous %> |
    <%= link_to 'Suivant >', peji_path(id: @peji.next.scan_number, chapter_id: @chapter.chapter_number), title: 'Suivant' if @peji.next %>
  </div>

</div>