config/routes.rb
Rails.application.routes.draw do

  #Index de tout le site
  root to: 'home#index'

  #Partie admin
  namespace :admin do
    resources :carousels
    resources :user, except: :index
    get '/users' => 'user#index', as: :admin_user_index
  end
  get '/admin' => 'admin#index', as: :admin_root

  #Différentes pages disponibles
  resources :magazines, path: 'webzines' do
    resources :pages
  end

  resources :mangas do
    resources :chapters, except: :show do
      resources :pejis, except: :show
    end
  end

  get '/mangas/:manga_id/:id' => 'chapters#show', as: :chapter
  get '/mangas/:manga_id/:chapter_id/:id' => 'pejis#show', as: :peji


  resources :presentations
  resources :blog

  # Partie contact
  get '/contact', to: 'contacts#new', as: :new_contact
  post '/contact', to: 'contacts#create', as: :contacts

  #Login + paramétrage des membres de KD
  devise_for :users
  get 'user/create'
  get '/membres' => 'user#index', as: :membres
  get '/membre/:id' => 'user#show', as: :membre
  get '/user/:id/edit_password' => 'user#password', as: :change_password
  resources :user, :controller => 'user'

  get '/mentions-legales', to: 'home#cgu', as: :cgu


end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  belongs_to :user
  mount_uploader :illu1, BlogUploader
  mount_uploader :illu2, BlogUploader
end

app/models/chapter.rb
class Chapter < ApplicationRecord

  has_many :pejis, :dependent => :destroy
  belongs_to :manga
  mount_uploader :apercu, ThumbnailUploader

end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :nom, :sujet, :email, :message

  validates :nom, :objet, :sujet, :email, :message, presence: true
  validates :email, :format => { :with => %r{.+@.+\..+} }, allow_blank: true

  def persisted?
    false
  end

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

end

app/models/magazine.rb
class Magazine < ApplicationRecord
  extend FriendlyId
  friendly_id :titre, use: :slugged
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader
  has_many :pages, :inverse_of => :magazine, :dependent => :destroy
  validates_uniqueness_of :slug


  def first_page
    self.pages.find_by(page_number: 1)
  end

end

app/models/manga.rb
class Manga < ApplicationRecord

  extend FriendlyId
  friendly_id :titre, use: :slugged
  validates_presence_of :slug

  has_many :chapters , :inverse_of => :manga, :dependent => :destroy
  mount_uploader :apercu, ThumbnailUploader
  mount_uploader :banniere, ThumbnailUploader

  has_and_belongs_to_many :users

end

app/models/page.rb
class Page < ApplicationRecord

  belongs_to :magazine
  validates_presence_of :magazine
  mount_uploader :image, PageUploader

  def previous
    self.class.where(page_number: (first.page_number - 1), magazine: first.magazine)
  end

  def next
    self.class.where(page_number: (first.page_number + 1), magazine: first.magazine)
  end

end

app/models/peji.rb
class Peji < ApplicationRecord

  belongs_to :chapter, :inverse_of => :pejis
  validates_presence_of :chapter
  mount_uploader :image, ScansUploader

  def previous
    self.class.where('scan_number < ?', scan_number).limit(1).first
  end

  def next
    self.class.where('scan_number > ?', scan_number).limit(1).last
  end

end

app/models/presentation.rb
class Presentation < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login

  has_and_belongs_to_many :mangas
  has_many :blogs

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :rememberable, :trackable, :validatable

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  validate :validate_username

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def self.all_except(user)
    where.not(id: user)
  end

end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :set_chapter, only: [:show, :edit, :update, :destroy]

  def index
    @manga = Manga.find(params[:manga_id])
    @chapters = Chapter.all
  end

  def show
  end

  def new
    @manga = Manga.find_by(slug: params[:manga_id])
    @chapter = Chapter.new

  end

  def edit
    @manga = Manga.find_by(slug: params[:manga_id])
  end

  def create
    @manga = Manga.friendly.find(params[:manga_id])
    @chapter = Chapter.new(chapter_params)
    @chapter.manga = @manga
    @chapter.chapter_number = @manga.chapters.count + 1

    if @chapter.save
      (params[:images] || []).each_with_index do |image, index|
        @chapter.pejis.create(image: image, scan_number: index + 1)
      end
      redirect_to chapter_path(manga_id: @manga, id: @chapter.chapter_number), notice: 'Chapter was successfully created.'
    else
      render :new
    end
  end

  def update
    if @chapter.update(chapter_params)
      (params[:images] || []).each_with_index do |image, index|
        @chapter.pejis.create(image: image, scan_number: index + 1)
      end
      redirect_to manga_chapter_path(@manga, @chapter), notice: 'Chapter was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @chapter.destroy
    redirect_to :back, notice: 'Chapter was successfully destroyed.'
  end

  private
    def set_chapter
      @manga = Manga.find_by(slug: params[:manga_id])
      @chapter = @manga.chapters.find_by(chapter_number: params[:id])
    end

    def chapter_params
      params.require(:chapter).permit(:titre, :apercu)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  #Retourne un titre
  def titre
    base_titre = 'Kippon Dream'
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/magazines_helper.rb
module MagazinesHelper
  def first_page
    self.pages.find_by(page_number: 1)
  end
end

app/helpers/mangas_helper.rb
module MangasHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pejis_helper.rb
module PejisHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/chapters/_form.html.erb
<%= form_for [@manga, @chapter] do |f| %>
    <% if @manga.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@manga.errors.count, "error") %> prohibited this peji from being saved:</h2>

          <ul>
            <% @manga.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <% if @chapter.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@chapter.errors.count, "error") %> prohibited this peji from being saved:</h2>

          <ul>
            <% @chapter.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

  <div class="field">
    <%= f.label :titre %>
    <%= f.text_field :titre %>
  </div>

  <div class="field">
    <%= f.label :apercu %>
    <%= f.file_field :apercu %>
  </div>

  <div class="field">
    <label for="images[]">Multi Upload</label>
    <%= file_field_tag 'images[]', type: :file, multiple: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chapters/edit.html.erb
<h1>Editing Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Show', @chapter %> |
<%= link_to 'Back', manga_path(@manga) %>

app/views/chapters/index.html.erb
<h1>Chapters</h1>
<% @manga.chapters.each do |chapter| %>
  <p>Titre : <%= chapter.titre %></p>
  <p>Apercu : <%= image_tag chapter.apercu, size: '100x100' %></p>
  <%= link_to 'Show', manga_chapter_path(@manga.id, chapter) %>
  <%= link_to 'Edit', edit_manga_chapter_path(@manga.id, chapter) %>
  <%= link_to 'Destroy', manga_chapter_path(@manga.id, chapter), method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>


<br>

<%= link_to 'New Chapter', new_manga_chapter_path %>

app/views/chapters/new.html.erb
<h1>New Chapter</h1>

<%= render 'form', chapter: @chapter %>

<%= link_to 'Back', manga_chapters_path %>

app/views/chapters/show.html.erb
<p>
  <strong>Titre:</strong>
  <%= @chapter.titre %>
</p>

<p>
  <strong>Apercu:</strong>
  <%= image_tag @chapter.apercu, size: '200x200' %>
</p>

<p>
  <strong>Images :</strong>
  <% @chapter.pejis.each do |p| %>

      <%= link_to peji_path(id: p.scan_number, chapter_id: @chapter.chapter_number) do %>
          <%= image_tag p.image, size: '100x100' %>
      <% end %>
  <% end %>
</p>

<%= link_to 'Edit', edit_manga_chapter_path %> |
<%= link_to 'Back', manga_chapters_path %>